### ISSUE TITLE
为什么从非关键帧开始裁剪 前面有一段时间画面全是灰色的？

### ISSUE THREAD

**Issue by renshou2003** [HuYuHua/simple_video_editor#1]
为什么从非关键帧开始裁剪 前面有一段时间画面全是灰色的？

**Comment by HuYuHua** [comment]
我这个是我自己用的。针对我自己录制的视频。 如果你用在其他视频的话得调整编码器的参数。
或者你把全部帧都重新编过，这比较耗时。

**Comment by renshou2003** [comment]
用ffmpeg录制的视频采用x264编码，需要调整些什么参数呢？你的程序从非关键帧裁剪的时候不就已经是重新编码了吗。

**Comment by HuYuHua** [comment]
我只是编码从裁剪的位置到下一个I帧。并不是全部重新编码。   我里面用的编码器不是x264。 你可以在里面改下用x264(有一个宏可以设置用x264)。

**Comment by renshou2003** [comment]
我一开始就是改成用x264的，但是前面总是有几秒钟是灰色的。搞不明白是是什么原因！

**Comment by HuYuHua** [comment]
那就应该是编码参数有不同的地方。具体得用工具对比两者的h264信息了。

**Comment by renshou2003** [comment]
好的，非常感谢！
